spring:
  application:
    name: worldBreaker
#  main:
#    log-startup-info:
#    banner-mode: off
logging:
  level:
    root: info
    org.springframework: error

world_stage:
  phase: 1
#  phase: 2
#  name: diy.txt # if phase == 2 , the value that can avilable
#  phase: 3 # all file pattern will avilable

server:
  port: 9000